//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGuardrail) DeepCopyInto(out *AIGuardrail) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGuardrail.
func (in *AIGuardrail) DeepCopy() *AIGuardrail {
	if in == nil {
		return nil
	}
	out := new(AIGuardrail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIGuardrail) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGuardrailCheck) DeepCopyInto(out *AIGuardrailCheck) {
	*out = *in
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make([]GuardrailPhase, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGuardrailCheck.
func (in *AIGuardrailCheck) DeepCopy() *AIGuardrailCheck {
	if in == nil {
		return nil
	}
	out := new(AIGuardrailCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGuardrailList) DeepCopyInto(out *AIGuardrailList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIGuardrail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGuardrailList.
func (in *AIGuardrailList) DeepCopy() *AIGuardrailList {
	if in == nil {
		return nil
	}
	out := new(AIGuardrailList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIGuardrailList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGuardrailNamespacedReference) DeepCopyInto(out *AIGuardrailNamespacedReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGuardrailNamespacedReference.
func (in *AIGuardrailNamespacedReference) DeepCopy() *AIGuardrailNamespacedReference {
	if in == nil {
		return nil
	}
	out := new(AIGuardrailNamespacedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGuardrailNemoProvider) DeepCopyInto(out *AIGuardrailNemoProvider) {
	*out = *in
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGuardrailNemoProvider.
func (in *AIGuardrailNemoProvider) DeepCopy() *AIGuardrailNemoProvider {
	if in == nil {
		return nil
	}
	out := new(AIGuardrailNemoProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGuardrailProvider) DeepCopyInto(out *AIGuardrailProvider) {
	*out = *in
	out.Nemo = in.Nemo
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGuardrailProvider.
func (in *AIGuardrailProvider) DeepCopy() *AIGuardrailProvider {
	if in == nil {
		return nil
	}
	out := new(AIGuardrailProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGuardrailSpec) DeepCopyInto(out *AIGuardrailSpec) {
	*out = *in
	out.Provider = in.Provider
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]AIGuardrailCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGuardrailSpec.
func (in *AIGuardrailSpec) DeepCopy() *AIGuardrailSpec {
	if in == nil {
		return nil
	}
	out := new(AIGuardrailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGuardrailStatus) DeepCopyInto(out *AIGuardrailStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGuardrailStatus.
func (in *AIGuardrailStatus) DeepCopy() *AIGuardrailStatus {
	if in == nil {
		return nil
	}
	out := new(AIGuardrailStatus)
	in.DeepCopyInto(out)
	return out
}
